image: lecondc/laradock

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: pyrunner_database
  MYSQL_ROOT_PASSWORD: local
  DB_HOST: mysql
  DB_USERNAME: root
  LANG: en_US.utf8
  LC_ALL: en_US.UTF-8
  LC_LANG: en_US.UTF-8

stages:
  - test

PHPunit (unit tests):
  stage: test
  only:
    - merge_requests

  script:
    - composer install
    - locale -a
    - python vendor/pveltrop/pyrunner/_cicd.py --phpunit

  artifacts:
    when: on_failure
    name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}_FAILED"
    paths:
      - "storage/logs/laravel.log"
      - ".env"
    untracked: false
    expire_in: 1 day

Pyrunner (browser tests):
  stage: test
  only:
    - merge_requests

  before_script:
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
    - echo 'Testing UTF-8'
    - python -c 'print(u"\u2122");'

  script:
    - composer install
    - locale -a
    - python vendor/pveltrop/pyrunner/_cicd.py --pyrunner

  artifacts:
    when: on_failure
    name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}_FAILED"
    paths:
      - "pyrunner.zip"
      - "record.mkv"
      - ".env"
      - "storage/logs/laravel.log"
    untracked: false
    expire_in: 1 day