# -*- coding: utf-8 -*-
import _init as pr
import requests
import random
from faker import Faker

fake = Faker('nl_NL')
pyAdminEmail = fake.email()
pyUserEmail = fake.email()
pyUserPassword = '12345678'
today = pr.datetime.today().strftime("%d")
skipFewDays = str(int(today)+5)

if pr.dev is not None:
    max_test_retries = 0
else:
    max_test_retries = 2
    
# -----------------------------------------------------------
# Refactoring/scanning
# -----------------------------------------------------------

def scan_for_dd():
    pr.start('Check if all dd() is removed from code')
    pr.step('Scan files with RegEx')
    pr.scan_regex(r"dd\(.*\)")
    pr.end('Check if all dd() is removed from code')
    
# -----------------------------------------------------------
# End of refactoring
# -----------------------------------------------------------

# -----------------------------------------------------------
# Tests
# -----------------------------------------------------------
        
def generate_tests_list():
    pr.start('Generate list with possible tests')
    pr.step('Fetching functions from Controllers & Models')
    pr.fetch_test_list(1,0)
    pr.end('Generate list with possible tests')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_register():
    pr.start('Users Can Register')
    pr.step('Go to register page') 
    pr.browser.get('http://localhost/register')
    pr.step('Company Name') 
    pr.type_xpath('//*[@id="name"]', fake.company())
    pr.step('KvK') 
    pr.type_xpath('//*[@id="kvk"]', 12345678)
    pr.step('Street') 
    pr.type_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr') 
    pr.type_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode') 
    pr.type_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City') 
    pr.type_xpath('//*[@id="city"]', fake.city())
    pr.step('Country') 
    pr.select_value_name('country', '155')
    pr.step('Contact Person') 
    pr.type_xpath('//*[@id="contact_person"]', fake.name())
    pr.step('Contact Person E-mail') 
    pr.type_xpath('//*[@id="contact_person_email"]', fake.email())
    pr.step('Contact Person Phone') 
    pr.type_xpath('//*[@id="contact_person_phone"]', fake.phone_number())
    pr.step('E-mail') 
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Password') 
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Password Confirm') 
    pr.type_xpath('//*[@id="password-confirm"]', pyUserPassword)
    pr.step('Register') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Registration Alert') 
    pr.find_xpath('/html/body/div/div/div/div[2]/div[2]/div/form/div[4]')
    pr.end('Users Can Register')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_request_password():
    pr.start('Users Can Request Password')
    pr.step('Logout first') 
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Click Password Forgot') 
    pr.click('/html/body/div/div/div/div[2]/div[2]/div/form/div[3]/a','.kt-login__link-forgot')
    pr.step('Password Forgot') 
    pr.browser.get('http://localhost/forgot/')
    pr.step('E-mail') 
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Request Password') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Password Alert') 
    pr.find_xpath('/html/body/div/div/div/div[2]/div[2]/div/form/div[4]')
    pr.end('Users Can Request Password')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_login():
    pr.start('Users Can Login')
    pr.step('Logout first') 
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Enter email') 
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password') 
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.end('Users Can Login')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_create_sending():
    pr.start('Users Can Create Sending')
    pr.step('Logout first') 
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get('http://localhost/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email') 
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password') 
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Find Sending Link With Translation') 
    pr.browser.find_element_by_xpath('/html/body/div[3]/div/div/div[2]/div/div[1]/div/div/ul[2]/li[3]/a[contains(.,"Aanmaken") or contains(.,"Create")]')
    pr.step('Go To Create Sending') 
    pr.browser.get('http://localhost/sending/create')
    pr.step('Pickup Contact Person') 
    pr.type_xpath('//*[@id="pickup_contact_person"]', fake.name())
    pr.step('Pickup Contact Phone') 
    pr.type_xpath('//*[@id="pickup_contact_phone"]', fake.phone_number())
    pr.step('Pickup Contact E-mail')
    pr.type_xpath('//*[@id="pickup_contact_email"]', fake.email())
    pr.step('Save Pickup Contact')
    pr.click('//*[@id="save_pickup_contact"]','#save_pickup_contact','save_pickup_contact')
    pr.step('Delivery Contact Person')
    pr.type_xpath('//*[@id="delivery_contact_person"]', fake.name())
    pr.step('Delivery Contact Phone')
    pr.type_xpath('//*[@id="delivery_contact_phone"]', fake.phone_number())
    pr.step('Delivery Contact E-mail')
    pr.type_xpath('//*[@id="delivery_contact_email"]', fake.email())
    pr.step('Save Delivery Contact')
    pr.click('//*[@id="save_delivery_contact"]','#save_delivery_contact','save_delivery_contact')
    pr.step('Auto Fill Pickup Company')
    pr.click('//*[@id="autofill_pickup"]','#autofill_pickup','autofill_pickup')
    pr.step('Pickup Loading Checkbox')
    pr.click('//*[@id="pickup_loading"]','#pickup_loading','pickup_loading')
    pr.step('Pickup Date')
    pr.change_text_xpath('//*[@id="pickup_date"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Pickup pr.Time ASAP')
    pr.click('//*[@id="pickup_time_asap_btn"]','#pickup_time_asap_btn','pickup_time_asap_btn')
    pr.step('Delivery Company')
    pr.type_xpath('//*[@id="delivery_company"]', fake.company())
    pr.step('Delivery Country')
    pr.select_value_name("delivery_country", "155")
    pr.step('Delivery Street')
    pr.type_xpath('//*[@id="delivery_street"]', fake.street_name())
    pr.step('Delivery House Nr')
    pr.type_xpath('//*[@id="delivery_housenr"]', "12D")
    pr.step('Delivery Zipcode')
    pr.type_xpath('//*[@id="delivery_zipcode"]', fake.postcode())
    pr.step('Delivery City')
    pr.type_xpath('//*[@id="delivery_city"]', fake.city())
    pr.step('Save Delivery Company')
    pr.click('//*[@id="save_delivery_company"]','#save_delivery_company','save_delivery_company')
    pr.step('Delivery Date From')
    pr.change_text_xpath('//*[@id="deadline_date_from"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Date Until')
    pr.change_text_xpath('//*[@id="deadline_date_until"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Time From')
    pr.type_xpath('//*[@id="input_deadline_time_from"]', "10:00")
    pr.step('Delivery Time Until')
    pr.type_xpath('//*[@id="input_deadline_time_until"]', "14:00")
    pr.step('Select inch')
    pr.select_value_name('dimensions_unit0', 'inch')
    pr.step('Pick Europallet')
    pr.select_value_name('content_type0', '3')
    pr.step('Fill in Amount')
    pr.type_xpath('//*[@id="amount"]', str(random.randint(1, 10)))
    pr.step('Fill in height')
    pr.type_xpath('//*[@id="dimensionsH"]', str(random.randint(10, 50)))
    pr.step('Fill in width')
    pr.type_xpath('//*[@id="dimensionsW"]', str(random.randint(10, 50)))
    pr.step('Fill in length')
    pr.type_xpath('//*[@id="dimensionsL"]', str(random.randint(10, 50)))
    pr.step('Fill in weight')
    pr.type_xpath('//*[@id="weight"]', str(random.randint(5, 70)))
    pr.step('Select lb')
    pr.select_value_name('weight_unit0', 'lb')
    pr.step('Request courier info')
    pr.click('//*[@id="courier_info_request"]','#courier_info_request','courier_info_request')
    pr.step('Check Vehicle: Side door')
    pr.click('//*[@id="vehicle_sidedoor"]','#vehicle_sidedoor','vehicle_sidedoor')
    pr.step('Check Vehicle: Cooling section')
    pr.click('//*[@id="vehicle_coolingsection"]','#vehicle_coolingsection','vehicle_coolingsection')
    pr.step('Extra comment')
    pr.type_xpath('//*[@id="extra_comment"]', fake.paragraphs(nb=1, ext_word_list=None))
    pr.step('Agree Terms')
    pr.click('//*[@id="agree_terms"]','#agree_terms','agree_terms')
    pr.step('Submit Sending')
    pr.click('//*[@id="submitSending"]','#submitSending','submitSending')
    pr.step('Sending in Datatable')
    pr.find_xpath('//*[@id="sendingsDatatable_wrapper"]')
    pr.end('Users Can Create Sending')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_view_profile():
    pr.start('Users Can View Profile')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get('http://localhost/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Click Gear Icon')
    pr.click('/html/body/div[3]/div/div/div[1]/div/div[2]/div[2]/div[1]','div.kt-header__topbar-item:nth-child(2) > div:nth-child(1)')
    pr.step('Click Profile')
    pr.click('/html/body/div[3]/div/div/div[1]/div/div[2]/div[2]/div[2]/div[2]/a','.kt-notification__item')
    pr.step('Go to Profile')
    pr.browser.get('http://localhost/profile/edit')
    pr.step('Change Country')
    pr.select_value_name('country', str(random.randint(1, 100)))
    pr.step('Change Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('Change House Nr')
    pr.change_text_xpath('//*[@id="housenr"]', str(random.randint(1, 100))+"D")
    pr.step('Change Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', str(random.randint(1000, 9999))+"NL")
    pr.step('Change City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Submit')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.end('Users Can View Profile')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_crud_address():
    pr.start('Users Can Create Address')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get('http://localhost/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Find Create Address')
    pr.find_xpath('//*[@id="kt_aside_menu"]/ul[3]/li[3]/a')
    pr.step('Go To Create Address')
    pr.browser.get('http://localhost/address/create')
    pr.step('Fill in Company Name')
    pr.type_xpath('//*[@id="company"]', fake.company())
    pr.step('Country')
    pr.select_value_name('company_country', str(random.randint(1, 100)))
    pr.step('Street')
    pr.type_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr')
    pr.type_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode')
    pr.type_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City')
    pr.type_xpath('//*[@id="city"]', fake.city())
    pr.step('Submit Address')
    pr.click('//*[@id="submitSending"]','#submitSending','submitSending')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    # pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Address datatable')
    pr.find_xpath('//*[@id="addressDatatable_wrapper"]')
    pr.end('Users Can Create Address')
    # Edit Address
    pr.start('Users Can Edit Address')
    pr.step('Click To Edit Address')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[8]/div/a','.divDTBlue > a:nth-child(1)')
    pr.step('Fill in Company Name')
    pr.change_text_xpath('//*[@id="company"]', fake.company())
    pr.step('Country')
    pr.select_value_name('company_country', str(random.randint(1, 100)))
    pr.step('Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr')
    pr.change_text_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Submit Address')
    pr.click('//*[@id="submitSending"]','#submitSending','submitSending')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Address datatable')
    pr.find_xpath('//*[@id="addressDatatable_wrapper"]')
    pr.end('Users Can Edit Address')
    # Delete Address
    pr.start('Users Can Delete Address')
    pr.step('Click To Edit Address')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[8]/div/a','tr.odd:nth-child(1) > td:nth-child(8) > div:nth-child(1) > a:nth-child(1)')
    pr.step('Delete Address')
    pr.click('//*[@id="deleteSending"]','#deleteSending','deleteSending')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Delete')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Address datatable')
    pr.find_xpath('//*[@id="addressDatatable_wrapper"]')
    pr.end('Users Can Delete Address')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_crud_contact():
    pr.start('Users Can Create Contact')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get('http://localhost/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Find Create Contact')
    pr.find_xpath('/html/body/div[3]/div/div/div[2]/div/div[1]/div/div/ul[4]/li[3]/a')
    pr.step('Go To Create Contact')
    pr.browser.get('http://localhost/contactperson/create')
    pr.step('Company')
    pr.select_index_id('company', "1")
    pr.step('Name')
    pr.type_xpath('//*[@id="name"]', fake.name())
    pr.step('Phone')
    pr.type_xpath('//*[@id="phone"]', fake.phone_number())
    pr.step('Email')
    pr.type_xpath('//*[@id="email"]', fake.email())
    pr.step('Submit Contact')
    pr.click('//*[@id="submitContact"]','#submitContact','submitContact')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Contact datatable')
    pr.find_xpath('//*[@id="contactsDatatable_wrapper"]')
    pr.end('Users Can Create Contact')
    # Edit Contact
    pr.start('Users Can Edit Contact')
    pr.step('Click To Edit Contact')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[6]/div/a','.divDTBlue > a:nth-child(1)')
    pr.step('Name')
    pr.change_text_xpath('//*[@id="name"]', fake.name())
    pr.step('Phone')
    pr.change_text_xpath('//*[@id="phone"]', fake.phone_number())
    pr.step('Email')
    pr.change_text_xpath('//*[@id="email"]', fake.email())
    pr.step('Submit Contact')
    pr.click('//*[@id="submitContact"]','#submitContact')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Contact datatable')
    pr.find_xpath('//*[@id="contactsDatatable_wrapper"]')
    pr.end('Users Can Edit Contact')
    # Delete Contact
    pr.start('Users Can Delete Contact')
    pr.step('Click To Delete Contact')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[6]/div/a','.divDTBlue > a:nth-child(1)')
    pr.step('Delete Contact')
    pr.click('//*[@id="deleteContact"]','#deleteContact','deleteContact')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Contact datatable')
    pr.find_xpath('//*[@id="contactsDatatable_wrapper"]')
    pr.end('Users Can Delete Contact')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_view_sending():
    pr.start('Users Can View Sending and Document')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get('http://localhost/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Find Sending Overview')
    pr.find_xpath('//*[@id="kt_aside_menu"]/ul[2]/li[2]/a')
    pr.step('Go to Sending Overview')
    pr.browser.get('http://localhost/sending')
    pr.step('View Sending')
    pr.click('//*[@id="sendingsDatatable"]/tbody/tr/td[12]/div/a','#sendingsDatatable > tbody > tr > td.editTD.clickable.text-center > div > a')
    pr.step('See information fields')
    pr.find_css('.showinfo')
    pr.step('Open sending document')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div[1]/a[2]','#sendingButtons > a:nth-child(2)')
    pr.step('Switch to Document tab')
    pr.switch_tab(1)
    pr.step('Find document field')
    pr.find_css('.g-aiPointText')
    pr.step('Back to Sending Overview tab')
    pr.switch_tab(0)
    pr.step('Back in Sending Overview')
    pr.find_css('.showinfo')
    pr.end('Users Can View Sending and Document')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_crud_admin():
    pr.start('Admins Can Create Admin')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get('http://localhost/_testing/pyloginadmin/')
    pr.step('Find Create Admin')
    pr.find_xpath('//*[@id="btnAdminCreate"]')
    pr.step('Go to Create Admin')
    pr.browser.get('http://localhost/admin/create')
    pr.step('Name')
    pr.type_xpath('//*[@id="name"]', fake.name())
    pr.step('Language')
    pr.select_index_id('language', '1')
    pr.step('E-mail')
    pr.type_xpath('//*[@id="email"]', fake.email())
    pr.step('Password')
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Password Confirm')
    pr.type_xpath('//*[@id="password-confirm"]', pyUserPassword)
    pr.step('Submit Admin')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Admin datatable')
    pr.find_xpath('//*[@id="adminsDatatable_wrapper"]')
    pr.end('Admins Can Create Admin')
    # Approve Admin
    pr.start('Admins Can Approve Admin')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[5]/div','tr.odd:nth-child(1) > td:nth-child(5) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Approve')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Active Admin')
    pr.find_css('.activeTd')
    pr.end('Admins Can Approve Admin')
    # Deny Admin
    pr.start('Admins Can Deny Admin')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[5]/div','tr.odd:nth-child(1) > td:nth-child(5) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Deny')
    pr.click('/html/body/div[5]/div/div[3]/button[2]','.swal2-cancel')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Active Admin')
    pr.find_css('.inactiveTd')
    pr.end('Admins Can Deny Admin')
    # Edit Admin
    pr.start('Admins Can Edit Admin')
    pr.step('Click on Edit')
    pr.click('//*[@id="adminsDatatable"]/tbody/tr[1]/td[6]/div/a','tr.odd:nth-child(1) > td:nth-child(6) > div:nth-child(1) > a:nth-child(1)')
    pr.step('Name')
    pr.change_text_xpath('//*[@id="name"]', fake.name())
    pr.step('Change Status To Active')
    pr.select_value_name('admin_rank', '1')
    pr.step('Click Reset Password')
    pr.click('//*[@id="passwordResetBtn"]','#passwordResetBtn','passwordResetBtn')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Submit Admin')
    pr.click('//*[@id="submitAdmin"]','#submitAdmin','submitAdmin')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Admin datatable')
    pr.find_xpath('//*[@id="adminsDatatable_wrapper"]')
    pr.step('Find Active Admin')
    pr.find_css('.activeTd')
    pr.end('Admins Can Edit Admin')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_crud_company():
    pr.start('Admins Can View Companies')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get('http://localhost/_testing/pyloginadmin/')
    pr.step('Find Company Overview')
    pr.find_xpath('//*[@id="btnCompanyOverview"]')
    pr.step('Go to Company Overview')
    pr.browser.get('http://localhost/company')
    pr.step('Company datatable')
    pr.find_xpath('//*[@id="companiesDatatable_wrapper"]')
    pr.end('Admins Can View Companies')
    # Approve Company
    pr.start('Admins Can Approve Company')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[10]/div','tr.odd:nth-child(1) > td:nth-child(10) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Approve')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Active Company')
    pr.find_css('.activeTd')
    pr.end('Admins Can Approve Company')
    # Deny Company
    pr.start('Admins Can Deny Company')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[10]/div','tr.odd:nth-child(1) > td:nth-child(10) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Deny')
    pr.click('/html/body/div[5]/div/div[3]/button[2]','.swal2-cancel')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Inactive Company')
    pr.find_css('.inactiveTd')
    pr.end('Admins Can Deny Company')
    # Edit Company
    pr.start('Admins Can Edit Company')
    pr.step('Click on Edit')
    pr.click('//*[@id="companiesDatatable"]/tbody/tr[1]/td[11]/div/a','#companiesDatatable > tbody > tr:nth-child(1) > td.editTD.clickable.text-center > div > a')
    pr.step('Company Name')
    pr.change_text_xpath('//*[@id="name"]', fake.company())
    pr.step('Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr')
    pr.change_text_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Country')
    pr.select_value_name('country', str(random.randint(1, 100)))
    pr.step('Click Reset Password')
    pr.click('//*[@id="passwordResetBtn"]','#passwordResetBtn','passwordResetBtn')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Submit Company')
    pr.click('//*[@id="submitCompany"]','#submitCompany','submitCompany')
    pr.time.sleep(2)
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','body > div.swal2-container.swal2-center.swal2-fade.swal2-shown > div > div.swal2-actions > button.swal2-confirm.swal2-styled')
    pr.step('Company datatable')
    pr.find_xpath('//*[@id="companiesDatatable_wrapper"]')
    pr.end('Admins Can Edit Company')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_edit_sending():
    pr.start('Admins Can Edit Sending')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get('http://localhost/_testing/pyloginadmin/')
    pr.step('Find Sending Overview Link')
    pr.find_css('#kt_aside_menu > ul:nth-child(2) > li.kt-menu__item > a')
    pr.step('Go to Sending Overview')
    pr.browser.get('http://localhost/sending')
    pr.step('Edit a sending')
    pr.click('//*[@id="sendingsDatatable"]/tbody/tr[1]/td[13]/div/a','td.editTD.clickable.text-center > div > a')
    pr.step('Pickup Contact Person')
    pr.change_text_xpath('//*[@id="pickup_contact_person"]', fake.name())
    pr.step('Pickup Contact Phone')
    pr.change_text_xpath('//*[@id="pickup_contact_phone"]', fake.phone_number())
    pr.step('Pickup Contact E-mail')
    pr.change_text_xpath('//*[@id="pickup_contact_email"]', fake.email())
    pr.step('Delivery Contact Person')
    pr.change_text_xpath('//*[@id="delivery_contact_person"]', fake.name())
    pr.step('Delivery Contact Phone')
    pr.change_text_xpath('//*[@id="delivery_contact_phone"]', fake.phone_number())
    pr.step('Delivery Contact E-mail')
    pr.change_text_xpath('//*[@id="delivery_contact_email"]', fake.email())
    pr.step('Pickup Loading Checkbox')
    pr.click('//*[@id="pickup_loading"]','#pickup_loading','pickup_loading')
    pr.step('Open Pickup Date')
    pr.browser.find_element_by_xpath('//*[@id="pickup_date"]').click()
    pr.step('Pickup Date')
    pr.change_text_xpath('//*[@id="pickup_date"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Pickup Time ASAP')
    pr.click('//*[@id="pickup_time_asap_btn"]','#pickup_time_asap_btn','pickup_time_asap_btn')
    pr.step('Delivery Company')
    pr.change_text_xpath('//*[@id="delivery_company"]', fake.company())
    pr.step('Delivery Country')
    pr.select_value_name("delivery_country", "155")
    pr.step('Delivery Street')
    pr.change_text_xpath('//*[@id="delivery_street"]', fake.street_name())
    pr.step('Delivery House Nr')
    pr.change_text_xpath('//*[@id="delivery_housenr"]', "12D")
    pr.step('Delivery Zipcode')
    pr.change_text_xpath('//*[@id="delivery_zipcode"]', fake.postcode())
    pr.step('Delivery City')
    pr.change_text_xpath('//*[@id="delivery_city"]', fake.city())
    pr.step('Delivery Date From')
    pr.change_text_xpath('//*[@id="deadline_date_from"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Date Until')
    pr.change_text_xpath('//*[@id="deadline_date_until"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Time From')
    pr.click('//*[@id="input_deadline_time_from"]','#input_deadline_time_from','input_deadline_time_from')
    pr.change_text_xpath('//*[@id="input_deadline_time_from"]', "10:00")
    pr.step('Delivery Time Until')
    pr.click('//*[@id="input_deadline_time_until"]','#input_deadline_time_until','input_deadline_time_until')
    pr.change_text_xpath('//*[@id="input_deadline_time_until"]', "14:00")
    pr.step('Select inch')
    pr.select_value_name('dimensions_unit0', 'inch')
    pr.step('Pick Europallet')
    pr.select_value_name('content_type0', '3')
    pr.step('Fill in Amount')
    pr.change_text_xpath('//*[@id="amount"]', str(random.randint(1, 10)))
    pr.step('Fill in height')
    pr.change_text_xpath('//*[@id="dimensionsH"]', str(random.randint(10, 50)))
    pr.step('Fill in width')
    pr.change_text_xpath('//*[@id="dimensionsW"]', str(random.randint(10, 50)))
    pr.step('Fill in length')
    pr.change_text_xpath('//*[@id="dimensionsL"]', str(random.randint(10, 50)))
    pr.step('Fill in weight')
    pr.change_text_xpath('//*[@id="weight"]', str(random.randint(5, 70)))
    pr.step('Select lb')
    pr.select_value_name('weight_unit0', 'lb')
    try:
        pr.step('Fill in courier name')
        pr.change_text_xpath('//*[@id="courier_name"]', fake.name())
        pr.step('Fill in courier phone')
        pr.change_text_xpath('//*[@id="courier_phone"]', fake.phone_number())
        pr.step('Fill in courier license plate')
        pr.change_text_xpath('//*[@id="courier_licenseplate"]', "NL664DD")
    except:
        print('Filling in courier failed. Either this wasnt requested or there is an error!')
        pr.time.sleep(5)
    pr.step('Check Vehicle: Side door')
    pr.click('//*[@id="vehicle_sidedoor"]','#vehicle_sidedoor','vehicle_sidedoor')
    pr.step('Check Vehicle: Cooling section')
    pr.click('//*[@id="vehicle_coolingsection"]','#vehicle_coolingsection','vehicle_coolingsection')
    pr.step('Enter a price')
    pr.type_xpath('//*[@id="sending_price"]', str(random.randint(1, 10000)))
    pr.step('Enter a tracking code')
    pr.type_xpath('//*[@id="tracking_code"]', "NL"+str(random.randint(1, 100000)))
    pr.step('Assign Price Given status')
    pr.select_value_name('sending_status', '2')
    pr.step('Extra comment')
    pr.change_text_xpath('//*[@id="extra_comment"]', fake.paragraphs(nb=1, ext_word_list=None))
    pr.step('Submit Sending')
    pr.click('//*[@id="submitSending"]','#submitSending','submitSending')
    pr.step('Sending in Datatable')
    pr.find_xpath('//*[@id="sendingsDatatable_wrapper"]')
    pr.end('Admins Can Edit Sending')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_approve_and_deny_sendings():
    pr.start('Users Can Approve And Deny Prices')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get('http://localhost/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.type_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.type_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Find Sending Overview')
    pr.find_xpath('//*[@id="kt_aside_menu"]/ul[2]/li[2]/a')
    pr.step('Go to Sending Overview')
    pr.browser.get('http://localhost/sending')
    pr.step('Fill with sending to agree and deny')
    pr.browser.get('http://localhost/_testing/createsendingswithprice')
    pr.step('Click on deny icon')
    pr.click('//*[@id="dnSndIcon"]','#dnSndIcon','dnSndIcon')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','body > div.swal2-container.swal2-center.swal2-fade.swal2-shown > div > div.swal2-actions > button.swal2-confirm.swal2-styled')
    pr.step('Success SweetAlert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(3)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','body > div.swal2-container.swal2-center.swal2-fade.swal2-shown > div > div.swal2-actions > button.swal2-confirm.swal2-styled')
    pr.step('See denied sending')
    pr.find_css('.priceDeniedStatus')
    pr.step('Click on approve icon')
    pr.click('//*[@id="apSndIcon"]','#apSndIcon','apSndIcon')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','body > div.swal2-container.swal2-center.swal2-fade.swal2-shown > div > div.swal2-actions > button.swal2-confirm.swal2-styled')
    pr.step('Get Terms and Conditions')
    pr.find_css('#swal2-content > a.mt-2')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','body > div.swal2-container.swal2-center.swal2-fade.swal2-shown > div > div.swal2-actions > button.swal2-confirm.swal2-styled')
    pr.step('Success SweetAlert')
    pr.find_css('.swal2-success-ring')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','body > div.swal2-container.swal2-center.swal2-fade.swal2-shown > div > div.swal2-actions > button.swal2-confirm.swal2-styled')
    pr.step('See approved sending')
    pr.find_css('.approvedStatus')
    pr.end('Users Can Approve And Deny Prices')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_change_status_modal():
    pr.start('Admins Can Change Status in Modal')
    pr.step('Logout first')
    pr.browser.get('http://localhost/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get('http://localhost/_testing/pyloginadmin/')
    pr.step('Find Sending Overview Link')
    pr.find_css('#kt_aside_menu > ul:nth-child(2) > li.kt-menu__item > a')
    pr.step('Go to Sending Overview')
    pr.browser.get('http://localhost/sending')
    pr.step('Open Status Modal')
    pr.click('//*[@id="sendingsDatatable"]/tbody/tr[1]/td[11]/div/p','#sendingsDatatable > tbody > tr:nth-child(1) > td.statusTD.openStatus.text-center > div > p')
    pr.step('Click on delivered status')
    pr.click('//*[@status="9"]','#statusList > button:nth-child(9)')
    pr.step('Success SweetAlert')
    pr.find_css('.swal2-success-ring')
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.end('Admins Can Change Status in Modal')
    
# -----------------------------------------------------------
# End of tests
# -----------------------------------------------------------

def RunTests():
    try:
        generate_tests_list()
        scan_for_dd()
        users_can_register()
        users_can_request_password()
        users_can_login()
        users_can_create_sending()
        users_can_create_priority_sending()
        users_can_view_profile()
        users_can_crud_address()
        users_can_crud_contact()
        users_can_view_sending()
        admins_can_crud_admin()
        admins_can_crud_company()
        admins_can_edit_sending()
        users_can_approve_and_deny_sendings()
        admins_can_change_status_modal()
    except Exception as e:
        if pr.dev is not None:
            print(' ')
            print(' ')
            print(pr.Fore.RED+str(e)+pr.Style.RESET_ALL)        
            print(' ')
            print(pr.Fore.CYAN+'Developing mode initialised')
            print('You can run tests individually, or run commands in _tests.py to make a new test, step by step')
            print('For example, try to run a test from the list in test_app.py, just type the following: (name_of_your_test)()')
            print('Or try to run a single command (located in _tests.py), for example: pr.click(element_to_click)'+pr.Style.RESET_ALL)
            print(' ')
            pr.ipdb.set_trace(context=1)
