# encoding=utf8
import _init as pr
import requests
import random
from faker import Faker

fake = Faker('nl_NL')
pyAdminEmail = fake.email()
pyUserEmail = fake.email()
pyUserPassword = '12345678'
today = pr.datetime.today().strftime("%d")
skipFewDays = str(int(today)+5)

if pr.dev is not None:
    max_test_retries = 0
else:
    max_test_retries = 2
    
# -----------------------------------------------------------
# Refactoring/scanning
# -----------------------------------------------------------

# Go to defined APP_URL in .env first
pr.get(pr.APP_URL)

def scan_for_dd():
    pr.start('Check if all dd() is removed from code')
    pr.step('Scan files with RegEx')
    pr.scan_regex(r"\sdd\(.*\)")
    pr.end('Check if all dd() is removed from code')
    
# -----------------------------------------------------------
# End of refactoring
# -----------------------------------------------------------

# -----------------------------------------------------------
# Tests
# -----------------------------------------------------------
        
def generate_tests_list():
    pr.start('Generate list with possible tests')
    pr.step('Fetching functions from Controllers & Models')
    pr.fetch_test_list(1,0)
    pr.end('Generate list with possible tests')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_register():
    pr.start('Users Can Register')
    pr.step('Go to register page') 
    pr.browser.get(pr.APP_URL+'/register')
    pr.step('Company Name') 
    pr.change_text_xpath('//*[@id="name"]', fake.company())
    pr.step('KvK') 
    pr.change_text_xpath('//*[@id="kvk"]', 12345678)
    pr.step('Street') 
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr') 
    pr.change_text_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode') 
    pr.change_text_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City') 
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Country') 
    pr.select_value_name('country', '155')
    pr.step('Contact Person') 
    pr.change_text_xpath('//*[@id="contact_person"]', fake.name())
    pr.step('Contact Person E-mail') 
    pr.change_text_xpath('//*[@id="contact_person_email"]', fake.email())
    pr.step('Contact Person Phone') 
    pr.change_text_xpath('//*[@id="contact_person_phone"]', fake.phone_number())
    pr.step('E-mail') 
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Password') 
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Password Confirm') 
    pr.change_text_xpath('//*[@id="password-confirm"]', pyUserPassword)
    pr.step('Register') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Registration Alert') 
    pr.find_xpath('/html/body/div/div/div/div[2]/div[2]/div/form/div[4]')
    pr.end('Users Can Register')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_request_password():
    pr.start('Users Can Request Password')
    pr.step('Logout first') 
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Click Password Forgot') 
    pr.click('/html/body/div/div/div/div[2]/div[2]/div/form/div[3]/a','.kt-login__link-forgot')
    pr.step('Password Forgot') 
    pr.browser.get(pr.APP_URL+'/forgot/')
    pr.step('E-mail') 
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Request Password') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Password Alert') 
    pr.find_xpath('/html/body/div/div/div/div[2]/div[2]/div/form/div[4]')
    pr.end('Users Can Request Password')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_login():
    pr.start('Users Can Login')
    pr.step('Logout first') 
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Enter email') 
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password') 
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.end('Users Can Login')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_create_sending():
    pr.start('Users Can Create Normal Sending')
    pr.step('Logout first') 
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email') 
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password') 
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Go To Create Sending') 
    pr.browser.get(pr.APP_URL+'/sending/create')
    pr.step('Normal Sending') 
    pr.browser.execute_script("$('input[name=normal_sending][id=normal_sending]').click()")
    pr.step('Pickup Contact Person') 
    pr.change_text_xpath('//*[@name="pickup_contact_person"]', fake.name())
    pr.step('Pickup Contact Phone') 
    pr.change_text_xpath('//*[@name="pickup_contact_phone"]', fake.phone_number())
    pr.step('Pickup Contact E-mail')
    pr.change_text_xpath('//*[@name="pickup_contact_email"]', fake.email())
    pr.step('Save Pickup Contact')
    pr.browser.execute_script("$('input[name=save_pickup_contact][id=save_pickup_contact]').click()")
    pr.step('Delivery Contact Person')
    pr.change_text_xpath('//*[@name="delivery_contact_person"]', fake.name())
    pr.step('Delivery Contact Phone')
    pr.change_text_xpath('//*[@name="delivery_contact_phone"]', fake.phone_number())
    pr.step('Delivery Contact E-mail')
    pr.change_text_xpath('//*[@name="delivery_contact_email"]', fake.email())
    pr.step('Save Delivery Contact')
    pr.browser.execute_script("$('input[name=save_delivery_contact][id=save_delivery_contact]').click()")
    pr.step('Auto Fill Pickup Company')
    pr.click('//.autoFillCompany[@side="pickup"]','#pickupDiv > div.kt-portlet__body.pb-0 > div > button')
    pr.step('Pickup Loading Checkbox')
    pr.browser.execute_script("$('input[name=pickup_loading][id=pickup_loading]').click()")
    pr.step('Pickup Date')
    pr.change_text_xpath('//*[@name="pickup_date"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Pickup Time From')
    pr.change_text_xpath('//*[@name="pickup_time_from"]', "10:00")
    pr.step('Delivery Company')
    pr.change_text_xpath('//*[@name="delivery_company"]', fake.company())
    pr.step('Delivery Country')
    pr.select_value_name("delivery_country", "155")
    pr.step('Delivery Street')
    pr.change_text_xpath('//*[@name="delivery_street"]', fake.street_name())
    pr.step('Delivery House Nr')
    pr.change_text_xpath('//*[@name="delivery_housenr"]', "12D")
    pr.step('Delivery Zipcode')
    pr.change_text_xpath('//*[@name="delivery_zipcode"]', fake.postcode())
    pr.step('Delivery City')
    pr.change_text_xpath('//*[@name="delivery_city"]', fake.city())
    pr.step('Save Delivery Company')
    pr.browser.execute_script("$('input[name=save_delivery_company][id=save_delivery_company]').click()")
    pr.step('Delivery Date From')
    pr.change_text_xpath('//*[@name="deadline_date_from"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Date Until')
    pr.change_text_xpath('//*[@name="deadline_date_until"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Time From')
    pr.change_text_xpath('//*[@name="deadline_time_from"]', "10:00")
    pr.step('Select inch')
    pr.select_value_name('dimensions_unit', 'inch')
    pr.step('Pick Europallet')
    pr.select_value_name('content_type', '3')
    pr.step('Fill in Amount')
    pr.change_text_xpath('//*[@name="amount"]', str(random.randint(1, 10)))
    pr.step('Fill in height')
    pr.change_text_xpath('//*[@name="dimensionsH"]', str(random.randint(10, 50)))
    pr.step('Fill in width')
    pr.change_text_xpath('//*[@name="dimensionsW"]', str(random.randint(10, 50)))
    pr.step('Fill in length')
    pr.change_text_xpath('//*[@name="dimensionsL"]', str(random.randint(10, 50)))
    pr.step('Fill in weight')
    pr.change_text_xpath('//*[@name="weight"]', str(random.randint(5, 70)))
    pr.step('Select lb')
    pr.select_value_name('weight_unit', 'lb')
    pr.step('Request courier info')
    pr.browser.execute_script("$('input[name=courier_info_request][id=courier_info_request]').click()")
    pr.step('Check Vehicle: Side door')
    pr.browser.execute_script("$('input[name=vehicle_sidedoor][id=vehicle_sidedoor]').click()")
    pr.step('Check Vehicle: Cooling section')
    pr.browser.execute_script("$('input[name=vehicle_coolingsection][id=vehicle_coolingsection]').click()")
    pr.step('Extra comment')
    pr.change_text_xpath('//*[@name="extra_comment"]', fake.paragraphs(nb=1, ext_word_list=None))
    pr.step('Agree Terms')
    pr.browser.execute_script("$('input[name=agree_terms][id=agree_terms]').click()")
    pr.step('Submit Sending')
    pr.click('//.form-group button[@type="submit"]','.form-group button[type="submit"]')
    pr.step('Success')
    pr.find_css('.swal2-success-ring')
    pr.end('Users Can Create Normal Sending')
    
@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_create_priority_sending():
    pr.start('Users Can Create Priority Sending')
    pr.step('Logout first') 
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email') 
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password') 
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login') 
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Go To Create Sending') 
    pr.browser.get(pr.APP_URL+'/sending/create')
    pr.step('Priority Sending') 
    pr.browser.execute_script("$('input[name=priority][id=priority_sending]').click()")
    pr.step('Pickup Contact Person') 
    pr.change_text_xpath('//*[@name="pickup_contact_person"]', fake.name())
    pr.step('Pickup Contact Phone') 
    pr.change_text_xpath('//*[@name="pickup_contact_phone"]', fake.phone_number())
    pr.step('Pickup Contact E-mail')
    pr.change_text_xpath('//*[@name="pickup_contact_email"]', fake.email())
    pr.step('Save Pickup Contact')
    pr.browser.execute_script("$('input[name=save_pickup_contact][id=save_pickup_contact]').click()")
    pr.step('Delivery Contact Person')
    pr.change_text_xpath('//*[@name="delivery_contact_person"]', fake.name())
    pr.step('Delivery Contact Phone')
    pr.change_text_xpath('//*[@name="delivery_contact_phone"]', fake.phone_number())
    pr.step('Delivery Contact E-mail')
    pr.change_text_xpath('//*[@name="delivery_contact_email"]', fake.email())
    pr.step('Save Delivery Contact')
    pr.browser.execute_script("$('input[name=save_delivery_contact][id=save_delivery_contact]').click()")
    pr.step('Auto Fill Pickup Company')
    pr.click('//.autoFillCompany[@side="pickup"]','#pickupDiv > div.kt-portlet__body.pb-0 > div > button')
    pr.step('Pickup Loading Checkbox')
    pr.browser.execute_script("$('input[name=pickup_loading][id=pickup_loading]').click()")
    pr.step('Delivery Company')
    pr.change_text_xpath('//*[@name="delivery_company"]', fake.company())
    pr.step('Delivery Country')
    pr.select_value_name("delivery_country", "155")
    pr.step('Delivery Street')
    pr.change_text_xpath('//*[@name="delivery_street"]', fake.street_name())
    pr.step('Delivery House Nr')
    pr.change_text_xpath('//*[@name="delivery_housenr"]', "12D")
    pr.step('Delivery Zipcode')
    pr.change_text_xpath('//*[@name="delivery_zipcode"]', fake.postcode())
    pr.step('Delivery City')
    pr.change_text_xpath('//*[@name="delivery_city"]', fake.city())
    pr.step('Save Delivery Company')
    pr.browser.execute_script("$('input[name=save_delivery_company][id=save_delivery_company]').click()")
    pr.step('Delivery Date From')
    pr.change_text_xpath('//*[@name="deadline_date_from"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Date Until')
    pr.change_text_xpath('//*[@name="deadline_date_until"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Select inch')
    pr.select_value_name('dimensions_unit', 'inch')
    pr.step('Pick Europallet')
    pr.select_value_name('content_type', '3')
    pr.step('Fill in Amount')
    pr.change_text_xpath('//*[@name="amount"]', str(random.randint(1, 10)))
    pr.step('Fill in height')
    pr.change_text_xpath('//*[@name="dimensionsH"]', str(random.randint(10, 50)))
    pr.step('Fill in width')
    pr.change_text_xpath('//*[@name="dimensionsW"]', str(random.randint(10, 50)))
    pr.step('Fill in length')
    pr.change_text_xpath('//*[@name="dimensionsL"]', str(random.randint(10, 50)))
    pr.step('Fill in weight')
    pr.change_text_xpath('//*[@name="weight"]', str(random.randint(5, 70)))
    pr.step('Select lb')
    pr.select_value_name('weight_unit', 'lb')
    pr.step('Request courier info')
    pr.browser.execute_script("$('input[name=courier_info_request][id=courier_info_request]').click()")
    pr.step('Check Vehicle: Side door')
    pr.browser.execute_script("$('input[name=vehicle_sidedoor_][id=vehicle_sidedoor_]').click()")
    pr.step('Check Vehicle: Cooling section')
    pr.browser.execute_script("$('input[name=vehicle_coolingsection][id=vehicle_coolingsection]').click()")
    pr.step('Extra comment')
    pr.change_text_xpath('//*[@name="extra_comment"]', fake.paragraphs(nb=1, ext_word_list=None))
    pr.step('Agree Terms')
    pr.browser.execute_script("$('input[name=agree_terms][id=agree_terms]').click()")
    pr.step('Submit Sending')
    pr.click('//.form-group button[@type="submit"]','.form-group button[type="submit"]')
    pr.step('Success')
    pr.find_css('.swal2-success-ring')
    pr.end('Users Can Create Priority Sending')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_view_profile():
    pr.start('Users Can View Profile')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.time.sleep(2)
    pr.step('Click Profile Icon')
    pr.click('//*span[title=User] i','span[title=User] i')
    pr.step('Click Profile')
    pr.click('//a[href="/profile/edit"]','a[href="/profile/edit"]')
    pr.step('Go to Profile')
    pr.browser.get(pr.APP_URL+'/profile/edit')
    pr.step('Change Country')
    pr.select_value_name('country', str(random.randint(1, 100)))
    pr.step('Change Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('Change House Nr')
    pr.change_text_xpath('//*[@id="housenr"]', str(random.randint(1, 100))+"D")
    pr.step('Change Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', str(random.randint(1000, 9999))+"NL")
    pr.step('Change City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Submit')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.end('Users Can View Profile')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_crud_address():
    pr.start('Users Can Create Address')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Find Create Address')
    pr.find_xpath('//*[@id="kt_aside_menu"]/ul[3]/li[3]/a')
    pr.step('Go To Create Address')
    pr.browser.get(pr.APP_URL+'/address/create')
    pr.step('Fill in Company Name')
    pr.change_text_xpath('//*[@id="company"]', fake.company())
    pr.step('Country')
    pr.select_value_name('company_country', str(random.randint(1, 100)))
    pr.step('Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr')
    pr.change_text_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Submit Address')
    pr.click('//*[@id="submitSending"]','#submitSending','submitSending')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Address datatable')
    pr.find_xpath('//*[@id="addressDatatable_wrapper"]')
    pr.end('Users Can Create Address')
    # Edit Address
    pr.start('Users Can Edit Address')
    pr.step('Click To Edit Address')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[8]/div/a','.divDTBlue > a:nth-child(1)')
    pr.time.sleep(5)
    pr.step('Fill in Company Name')
    pr.change_text_xpath('//*[@id="company"]', fake.company())
    pr.step('Country')
    pr.select_value_name('company_country', str(random.randint(1, 100)))
    pr.step('Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr')
    pr.change_text_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Submit Address')
    pr.click('//*[@id="submitSending"]','#submitSending','submitSending')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Address datatable')
    pr.find_xpath('//*[@id="addressDatatable_wrapper"]')
    pr.end('Users Can Edit Address')
    # Delete Address
    pr.start('Users Can Delete Address')
    pr.step('Click To Edit Address')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[8]/div/a','tr.odd:nth-child(1) > td:nth-child(8) > div:nth-child(1) > a:nth-child(1)')
    pr.time.sleep(3)
    pr.step('Delete Address')
    pr.click('//*[@id="deleteSending"]','#deleteSending','deleteSending')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click Delete')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Address datatable')
    pr.find_xpath('//*[@id="addressDatatable_wrapper"]')
    pr.end('Users Can Delete Address')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_crud_contact():
    pr.start('Users Can Create Contact')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Go To Create Contact')
    pr.browser.get(pr.APP_URL+'/contactperson/create')
    pr.time.sleep(2)
    pr.step('Company')
    pr.select_index_id('company', "1")
    pr.step('Name')
    pr.change_text_xpath('//*[@id="name"]', fake.name())
    pr.step('Phone')
    pr.change_text_xpath('//*[@id="phone"]', fake.phone_number())
    pr.step('Email')
    pr.change_text_xpath('//*[@id="email"]', fake.email())
    pr.step('Submit Contact')
    pr.click('//*[@id="submitContact"]','#submitContact','submitContact')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Contact datatable')
    pr.find_xpath('//*[@id="contactsDatatable_wrapper"]')
    pr.end('Users Can Create Contact')
    # Edit Contact
    pr.start('Users Can Edit Contact')
    pr.step('Click To Edit Contact')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[6]/div/a','.divDTBlue > a:nth-child(1)')
    pr.time.sleep(2)
    pr.step('Name')
    pr.change_text_xpath('//*[@id="name"]', fake.name())
    pr.step('Phone')
    pr.change_text_xpath('//*[@id="phone"]', fake.phone_number())
    pr.step('Email')
    pr.change_text_xpath('//*[@id="email"]', fake.email())
    pr.step('Submit Contact')
    pr.click('//*[@id="submitContact"]','#submitContact')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Contact datatable')
    pr.find_xpath('//*[@id="contactsDatatable_wrapper"]')
    pr.end('Users Can Edit Contact')
    # Delete Contact
    pr.start('Users Can Delete Contact')
    pr.step('Click To Delete Contact')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr/td[6]/div/a','.divDTBlue > a:nth-child(1)')
    pr.time.sleep(2)
    pr.step('Delete Contact')
    pr.click('//*[@id="deleteContact"]','#deleteContact','deleteContact')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Contact datatable')
    pr.find_xpath('//*[@id="contactsDatatable_wrapper"]')
    pr.end('Users Can Delete Contact')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_view_sending():
    pr.start('Users Can View Sending and Document')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'').text
    pr.step('Enter email')
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Go to Sending Overview')
    pr.browser.get(pr.APP_URL+'/sending')
    pr.time.sleep(2)
    pr.step('View Sending')
    pr.click('//*[@id="sendingsDatatable"]/tbody/tr/td[12]/div/a','#sendingsDatatable > tbody > tr > td.editTD.clickable.text-center > div > a')
    pr.time.sleep(2)
    pr.step('See information fields')
    pr.find_css('.showsending')
    pr.step('Open sending document')
    pr.click('//a[shippingdocument]','a[shippingdocument]')
    pr.step('Switch to Document tab')
    pr.switch_tab(1)
    pr.step('Find document field')
    pr.find_css('.g-aiPointText')
    pr.step('Back to Sending Overview tab')
    pr.switch_tab(0)
    pr.step('Back in Sending Overview')
    pr.find_css('.showsending')
    pr.end('Users Can View Sending and Document')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_crud_admin():
    pr.start('Admins Can Create Admin')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get(pr.APP_URL+'/_testing/pyloginadmin/')
    pr.step('Find Create Admin')
    pr.find_xpath('//*[@id="btnAdminCreate"]')
    pr.step('Go to Create Admin')
    pr.browser.get(pr.APP_URL+'/admin/create')
    pr.step('Name')
    pr.change_text_xpath('//*[@id="name"]', fake.name())
    pr.step('Language')
    pr.select_index_id('language', '1')
    pr.step('E-mail')
    pr.change_text_xpath('//*[@id="email"]', fake.email())
    pr.step('Password')
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Password Confirm')
    pr.change_text_xpath('//*[@id="password-confirm"]', pyUserPassword)
    pr.step('Submit Admin')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Admin datatable')
    pr.find_xpath('//*[@id="adminsDatatable_wrapper"]')
    pr.end('Admins Can Create Admin')
    # Approve Admin
    pr.start('Admins Can Approve Admin')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[5]/div','tr.odd:nth-child(1) > td:nth-child(5) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click Approve')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Active Admin')
    pr.find_css('.activeTd')
    pr.end('Admins Can Approve Admin')
    # Deny Admin
    pr.start('Admins Can Deny Admin')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[5]/div','tr.odd:nth-child(1) > td:nth-child(5) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Deny')
    pr.click('/html/body/div[5]/div/div[3]/button[2]','.swal2-cancel')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Active Admin')
    pr.find_css('.inactiveTd')
    pr.end('Admins Can Deny Admin')
    # Edit Admin
    pr.start('Admins Can Edit Admin')
    pr.step('Click on Edit')
    pr.click('//*[@id="adminsDatatable"]/tbody/tr[1]/td[6]/div/a','tr.odd:nth-child(1) > td:nth-child(6) > div:nth-child(1) > a:nth-child(1)')
    pr.step('Name')
    pr.change_text_xpath('//*[@id="name"]', fake.name())
    pr.step('Change Status To Active')
    pr.select_value_name('admin_rank', '1')
    pr.step('Click Reset Password')
    pr.click('//*[@id="passwordResetBtn"]','#passwordResetBtn','passwordResetBtn')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Submit Admin')
    pr.click('//*[@id="submitAdmin"]','#submitAdmin','submitAdmin')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Back to Admin datatable')
    pr.find_xpath('//*[@id="adminsDatatable_wrapper"]')
    pr.step('Find Active Admin')
    pr.find_css('.activeTd')
    pr.end('Admins Can Edit Admin')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_crud_company():
    pr.start('Admins Can View Companies')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get(pr.APP_URL+'/_testing/pyloginadmin/')
    pr.step('Find Company Overview')
    pr.find_xpath('//*[@id="btnCompanyOverview"]')
    pr.step('Go to Company Overview')
    pr.browser.get(pr.APP_URL+'/company')
    pr.step('Company datatable')
    pr.find_xpath('//*[@id="companiesDatatable_wrapper"]')
    pr.end('Admins Can View Companies')
    # Approve Company
    pr.start('Admins Can Approve Company')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[10]/div','tr.odd:nth-child(1) > td:nth-child(10) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click Approve')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Active Company')
    pr.find_css('.activeTd')
    pr.end('Admins Can Approve Company')
    # Deny Company
    pr.start('Admins Can Deny Company')
    pr.step('Click on Status')
    pr.click('/html/body/div[3]/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/table/tbody/tr[1]/td[10]/div','tr.odd:nth-child(1) > td:nth-child(10) > div:nth-child(1)')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.step('Click Deny')
    pr.click('/html/body/div[5]/div/div[3]/button[2]','.swal2-cancel')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Find Inactive Company')
    pr.find_css('.inactiveTd')
    pr.end('Admins Can Deny Company')
    # Edit Company
    pr.start('Admins Can Edit Company')
    pr.step('Click on Edit')
    pr.click('//*[@id="companiesDatatable"]/tbody/tr[1]/td[11]/div/a','#companiesDatatable > tbody > tr:nth-child(1) > td.editTD.clickable.text-center > div > a')
    pr.time.sleep(2)
    pr.step('Company Name')
    pr.change_text_xpath('//*[@id="name"]', fake.company())
    pr.step('Street')
    pr.change_text_xpath('//*[@id="street"]', fake.street_name())
    pr.step('House nr')
    pr.change_text_xpath('//*[@id="housenr"]', '12D')
    pr.step('Zipcode')
    pr.change_text_xpath('//*[@id="zipcode"]', fake.postcode())
    pr.step('City')
    pr.change_text_xpath('//*[@id="city"]', fake.city())
    pr.step('Country')
    pr.select_value_name('country', str(random.randint(1, 100)))
    pr.step('Click Reset Password')
    pr.click('//*[@id="passwordResetBtn"]','#passwordResetBtn','passwordResetBtn')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Submit Company')
    pr.click('//*[@id="submitCompany"]','#submitCompany','submitCompany')
    pr.time.sleep(2)
    pr.step('Success Sweetalert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Company datatable')
    pr.find_xpath('//*[@id="companiesDatatable_wrapper"]')
    pr.end('Admins Can Edit Company')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_edit_sending():
    pr.start('Admins Can Edit Sending')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get(pr.APP_URL+'/_testing/pyloginadmin/')
    pr.step('Find Sending Overview Link')
    pr.find_css('#kt_aside_menu > ul:nth-child(2) > li.kt-menu__item > a')
    pr.step('Go to Sending Overview')
    pr.browser.get(pr.APP_URL+'/sending')
    pr.time.sleep(2)
    pr.step('Edit a sending')
    pr.click('//.divDTBlue','.divDTBlue')
    pr.time.sleep(2)
    pr.step('Pickup Contact Person')
    pr.change_text_xpath('//*[@name="pickup_contact_person"]', fake.name())
    pr.step('Pickup Contact Phone')
    pr.change_text_xpath('//*[@name="pickup_contact_phone"]', fake.phone_number())
    pr.step('Pickup Contact E-mail')
    pr.change_text_xpath('//*[@name="pickup_contact_email"]', fake.email())
    pr.step('Delivery Contact Person')
    pr.change_text_xpath('//*[@name="delivery_contact_person"]', fake.name())
    pr.step('Delivery Contact Phone')
    pr.change_text_xpath('//*[@name="delivery_contact_phone"]', fake.phone_number())
    pr.step('Delivery Contact E-mail')
    pr.change_text_xpath('//*[@name="delivery_contact_email"]', fake.email())
    pr.step('Pickup Loading Checkbox')
    pr.browser.execute_script("$('input[name=pickup_loading][id=pickup_loading]').click()")
    try:
        pr.step('Open Pickup Date')
        pr.browser.find_element_by_xpath('//*[@name="pickup_date"]').click()
        pr.step('Pickup Date')
        pr.change_text_xpath('//*[@name="pickup_date"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
        pr.step('Pickup Time From')
        pr.change_text_xpath('//*[@name="pickup_time_from"]', "11:00")
        pr.step('Pickup Time Until')
        pr.change_text_xpath('//*[@name="pickup_time_until"]', "15:00")
    except:
        print('Pickup time not changed. Perhaps this is a priority sending?')
    pr.step('Delivery Company')
    pr.change_text_xpath('//*[@name="delivery_company"]', fake.company())
    pr.step('Delivery Country')
    pr.select_value_name("delivery_country", "155")
    pr.step('Delivery Street')
    pr.change_text_xpath('//*[@name="delivery_street"]', fake.street_name())
    pr.step('Delivery House Nr')
    pr.change_text_xpath('//*[@name="delivery_housenr"]', "12D")
    pr.step('Delivery Zipcode')
    pr.change_text_xpath('//*[@name="delivery_zipcode"]', fake.postcode())
    pr.step('Delivery City')
    pr.change_text_xpath('//*[@name="delivery_city"]', fake.city())
    pr.step('Delivery Date From')
    pr.change_text_xpath('//*[@name="deadline_date_from"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Date Until')
    pr.change_text_xpath('//*[@name="deadline_date_until"]',pr.datetime.today().strftime("%Y-%m-")+skipFewDays)
    pr.step('Delivery Time From')
    pr.click('//*[@name="deadline_time_from"]','#deadline_time_from','deadline_time_from')
    pr.change_text_xpath('//*[@name="deadline_time_from"]', "10:00")
    pr.step('Select inch')
    pr.select_value_name('dimensions_unit', 'inch')
    pr.step('Pick Europallet')
    pr.select_value_name('content_type', '3')
    pr.step('Fill in Amount')
    pr.change_text_xpath('//*[@name="amount"]', str(random.randint(1, 10)))
    pr.step('Fill in height')
    pr.change_text_xpath('//*[@name="dimensionsH"]', str(random.randint(10, 50)))
    pr.step('Fill in width')
    pr.change_text_xpath('//*[@name="dimensionsW"]', str(random.randint(10, 50)))
    pr.step('Fill in length')
    pr.change_text_xpath('//*[@name="dimensionsL"]', str(random.randint(10, 50)))
    pr.step('Fill in weight')
    pr.change_text_xpath('//*[@name="weight"]', str(random.randint(5, 70)))
    pr.step('Select lb')
    pr.select_value_name('weight_unit', 'lb')
    try:
        pr.step('Fill in courier name')
        pr.change_text_xpath('//*[@name="courier_name"]', fake.name())
        pr.step('Fill in courier phone')
        pr.change_text_xpath('//*[@name="courier_phone"]', fake.phone_number())
        pr.step('Fill in courier license plate')
        pr.change_text_xpath('//*[@name="courier_licenseplate"]', "NL664DD")
    except:
        print('Filling in courier failed. Either this wasnt requested or there is an error!')
        pr.time.sleep(5)
    pr.step('Check Vehicle: Side door')
    pr.browser.execute_script("$('input[name=vehicle_sidedoor][id=vehicle_sidedoor]').click()")
    pr.step('Check Vehicle: Cooling section')
    pr.browser.execute_script("$('input[name=vehicle_coolingsection][id=vehicle_coolingsection]').click()")
    pr.step('Enter a price')
    pr.change_text_xpath('//*[@id="sending_price"]', str(random.randint(1, 999)))
    pr.step('Enter a tracking code')
    pr.change_text_xpath('//*[@id="tracking_code"]', "NL"+str(random.randint(1, 100000)))
    pr.step('Assign Price Given status')
    pr.select_value_name('sending_status', '2')
    pr.step('Extra comment')
    pr.change_text_xpath('//*[@id="extra_comment"]', fake.paragraphs(nb=1, ext_word_list=None))
    pr.step('Submit Sending')
    pr.click('//.form-group button[@type="submit"]','.form-group button[type="submit"]')
    pr.step('Success')
    pr.find_css('.swal2-success')
    pr.end('Admins Can Edit Sending')

@pr.retry(stop_max_attempt_number=max_test_retries)
def users_can_approve_and_deny_sendings():
    pr.start('Users Can Approve And Deny Prices')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Authenticate This User') 
    requests.get(pr.APP_URL+'/_testing/pyauthenticate/'+pyUserEmail+'')
    pr.step('Enter email')
    pr.change_text_xpath('//*[@id="email"]', pyUserEmail)
    pr.step('Enter password')
    pr.change_text_xpath('//*[@id="password"]', pyUserPassword)
    pr.step('Login')
    pr.click('//*[@id="kt_login_signin_submit"]','#kt_login_signin_submit','kt_login_signin_submit')
    pr.step('Go to Sending Overview')
    pr.browser.get(pr.APP_URL+'/sending')
    pr.time.sleep(2)
    pr.step('Fill with sending to agree and deny')
    pr.browser.get(pr.APP_URL+'/_testing/createsendingswithprice')
    pr.step('Click on deny icon')
    pr.click('//*[@id="dnSndIcon"]','#dnSndIcon','dnSndIcon')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success SweetAlert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(3)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('See denied sending')
    pr.find_css('.priceDeniedStatus')
    pr.step('Click on approve icon')
    pr.click('//*[@id="apSndIcon"]','#apSndIcon','apSndIcon')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Get Terms and Conditions')
    pr.find_css('#swal2-content > a.mt-2')
    pr.step('Get Warning')
    pr.find_css('.swal2-warning')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('Success SweetAlert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.step('See approved sending')
    pr.find_css('.approvedStatus')
    pr.end('Users Can Approve And Deny Prices')

@pr.retry(stop_max_attempt_number=max_test_retries)
def admins_can_change_status_modal():
    pr.start('Admins Can Change Status in Modal')
    pr.step('Logout first')
    pr.browser.get(pr.APP_URL+'/_testing/pylogout')
    pr.step('Login as Admin')
    pr.browser.get(pr.APP_URL+'/_testing/pyloginadmin/')
    pr.step('Go to Sending Overview')
    pr.browser.get(pr.APP_URL+'/sending')
    pr.time.sleep(2)
    pr.step('Open Status Modal')
    pr.click('//*[@id="sendingsDatatable"]/tbody/tr[1]/td[11]/div/p','#sendingsDatatable > tbody > tr:nth-child(1) > td.statusTD.openStatus.text-center > div > p')
    pr.time.sleep(2)
    pr.step('Click on delivered status')
    pr.click('//*[@status="9"]','#statusList > button:nth-child(9)')
    pr.step('Success SweetAlert')
    pr.find_css('.swal2-success-ring')
    pr.time.sleep(2)
    pr.step('Click OK')
    pr.click('/html/body/div[5]/div/div[3]/button[1]','.swal2-confirm')
    pr.end('Admins Can Change Status in Modal')
    
# -----------------------------------------------------------
# End of tests
# -----------------------------------------------------------

# Make sure you have this exact function name with your test functions in it!
# PyRunner and CI/CD will always look for this function

def RunTests():
    generate_tests_list()
    scan_for_dd()
    users_can_register()
    users_can_request_password()
    users_can_login()
    users_can_create_sending()
    users_can_create_priority_sending()
    users_can_view_profile()
    users_can_crud_address()
    users_can_crud_contact()
    users_can_view_sending()
    admins_can_crud_admin()
    admins_can_crud_company()
    admins_can_edit_sending()
    users_can_approve_and_deny_sendings()
    admins_can_change_status_modal()